server:
  port: 8082
spring:
  application:
    name: car-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://car-db:3306/car-service
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka